import type { Metadata } from "next";
import { DM_Sans, Alumni_Sans_SC, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers/Providers";
import { ToastContainer } from "react-toastify";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500","600", "700", "800", "900"],
  variable: "--font-dm-sans",
});

const alumniSans = Alumni_Sans_SC({
  subsets: ["latin"],
  weight: ["400", "500","600", "700", "800", "900"],
  variable: "--font-alumni-sans",
  display: "swap",
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500","600", "700", "800"],
  variable: "--font-plus-jakarta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${alumniSans.variable} ${plusJakarta.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        {/* {children} */}

        {/* Toast Container for toast messages */}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          newestOnTop
          closeOnClick
          pauseOnHover
          draggable
        />
      </body>
    </html>
  );
}
